### ISSUE TITLE
Include Emoji Codes in Data

### ISSUE THREAD

**Issue by idleberg** [kcsaff/emojitations#1]
I'm not sure whether I understand the purpose of `codepoints`, but I was wondering why the data doesn't include the codes for each emoji (e.g. `U+1F600` for _grinning face_). I guess, for the sake of completion, the year could be included as well.

**Comment by idleberg** [comment]
Oh, I get it now. The `codepoints` are the decimal representation of the codes listed in the [full emoji list](http://unicode.org/emoji/charts/full-emoji-list.html).

**Comment by kcsaff** [comment]
I suppose I should write better comments to clear up such confusions, eh?
